/*
-- CarePlan Mst
drop table if exists careplan_mst;
*/

-- Diagnosis Mst
CREATE TABLE IF NOT EXISTS careplan_mst(
    --Main Columns
    name VARCHAR(200),
    to_be_print bool DEFAULT TRUE NOT NULL,

    --Inherited Columns
    tran_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_active bool DEFAULT TRUE NOT NULL
);
