/*
drop table if exists case_mst;
drop index if exists idx_case_mst_patient_id;
*/

CREATE TABLE IF NOT EXISTS case_mst(
    tran_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_active bool DEFAULT TRUE NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(1000),
    patient_id BIGINT NOT NULL,
    office_id BIGINT NOT NULL,
    note varchar(1000),

    CONSTRAINT fk_case_mst_patient_mst_sb_tran_id FOREIGN KEY(patient_id) REFERENCES patient_mst_sb(tran_id),
    CONSTRAINT fk_case_mst_office_mst_sb_tran_id FOREIGN KEY(office_id) REFERENCES office_mst_sb(tran_id)
);

CREATE INDEX IF NOT EXISTS idx_case_mst_patient_id ON case_mst (patient_id);