/*
drop table if exists icd_mst;
drop index if exists idx_icd_mst_code_is_active;
*/

CREATE TABLE IF NOT EXISTS icd_mst(
    tran_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_active bool DEFAULT TRUE NOT NULL,
--Main Columns
    code varchar(20) NOT NULL UNIQUE,
    description varchar(500),
    note varchar(1000),
    expired_at date
);

CREATE INDEX IF NOT EXISTS idx_icd_mst_code_is_active ON icd_mst (code, is_active);