/*
-- VnLabOrder Mst
drop table if exists vn_lab_order;
drop index if exists vn_lab_order_pn_id_lab_order_id;
*/

-- VisitNote Lab Order Hdr
CREATE TABLE IF NOT EXISTS vn_lab_order(
    --Main Columns
    pn_id BIGINT,
    lab_order_id BIGINT,
    taken_at TIMESTAMP,
    note VARCHAR(1000),

    --Inherited Columns
    tran_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_active bool DEFAULT TRUE NOT NULL,

    CONSTRAINT fk_vn_lab_order_visit_note_tran_id FOREIGN KEY (pn_id) REFERENCES visit_note(tran_id),
    CONSTRAINT fk_vn_lab_order_lab_order_hdr_tran_id FOREIGN KEY (lab_order_id) REFERENCES lab_order_hdr(tran_id)
);

CREATE INDEX IF NOT EXISTS idx_vn_lab_order_pn_id_lab_order_id on vn_lab_order(pn_id desc, lab_order_id desc);
