/*
-- VnLabOrder Mst
drop table if exists vn_lab_order_icd_map;
drop index if exists vn_lab_order_pn_id_lab_order_id;
*/

-- VisitNote Lab Order Icd Map
CREATE TABLE IF NOT EXISTS vn_lab_order_icd_map(
    --Main Columns
    vn_lab_order_id BIGINT NOT NULL,
    icd_id BIGINT NOT NULL,
    seq BIGINT NOT NULL,

    --Inherited Columns
    tran_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_active bool DEFAULT TRUE NOT NULL,

--Foreign key constraints
    CONSTRAINT fk_vn_lab_order_icd_map_vn_lab_order_tran_id FOREIGN KEY(vn_lab_order_id) REFERENCES vn_lab_order(tran_id),
    CONSTRAINT fk_vn_lab_order_icd_map_icd_mst_tran_id FOREIGN KEY(icd_id) REFERENCES icd_mst(tran_id),
--General
    CONSTRAINT chk_vn_lab_order_icd_map_seq_1_to_8 CHECK(seq >=1 AND seq<=8),
--Unique constraint
    CONSTRAINT uk_vn_lab_order_icd_map_vn_lab_order_id_seq UNIQUE(vn_lab_order_id, seq)
);

CREATE INDEX IF NOT EXISTS idx_vn_lab_order_icd_map_vn_lab_order_id_icd_id ON vn_lab_order_icd_map (vn_lab_order_id, icd_id);
