#////////////////////////////////////////////////
#//
#// Name: IMS_Project application.properties
#//
#// Description: properties for whole project
#//
#// Version history:
#//
#// v1.0 || type : New Func || Mar 16, 2026 || TaukirS (ER 1101 - Patient Master Base Changes in SB project)
#// v1.1 || type : Change ||  Mar 29, 2026 || TaukirS (ER 1104 - Jwt Authentication integration changes)
#// v1.2 || type : Change || Apr 01, 2026 || TaukirS (ER 1107 - API gateway config changes)
#////////////////////////////////////////////////

spring.application.name=ims-project

#change the server access port to run, because by default it runs in 8080, and in that jenkins is running
server.port=8081

#Logging file directory path
logging.file.name=logs/errorLog.log

#default path for this project
#//Apr 01, 2026 TaukirS (ER 1107 - API gateway config changes) - have to change contextpath to ims, as its configured the same in api gatewway config
server.servlet.context-path=/ims

#Postgres DB connection configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/practice_ims
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#configuration to setup swagger page
springdoc.swagger-ui.use-root-path=true
springdoc.writer-default-pretty-printer=true
springdoc.swagger-ui,disable-swagger-default-url=true

#Swagger Configuration
springdoc.swagger-ui.path=/public/swagger-ui.html
springdoc.api-docs.path=/public/v3/api-docs

#// Start Mar 29, 2026 TaukirS (ER 1104 - Jwt Authentication integration changes)
#Jwt Token Configuration
jwt.secretKey=fsukewr87328o4u32kfjsdkmfskdufoiwe7832829r2-=fsdfksldfksd87urio32uriowsejfklj3oi4ru90828u4i23u
#// End Mar 29, 2026 TaukirS (ER 1104 - Jwt Authentication integration changes)

#logging.level.org.springdoc=DEBUG
#logging.level.org.springframework.web=DEBUG

#//Apr 01, 2026 TaukirS (ER 1107 - API gateway config changes) - api gateway config changes
eureka.instance.prefer-ip-address=true

#To run the application in debug mode
#debug=true