#////////////////////////////////////////////////
#//
#// Name:Application.properties
#//
#// Description: properties for whole project
#//
#// Version history:
#//
#// v1.0 || type : New Func || Mar 16, 2026 || TaukirS (ER 1101 - Patient Master Base Changes in SB project)
#////////////////////////////////////////////////

spring.application.name=Ims_Project

#change the server access port to run, because by default it runs in 8080, and in that jenkins is running
server.port=8081

#Logging file directory path
logging.file.name=logs/errorLog.log

#default path for this project
server.servlet.context-path=/api

#Postgres DB connection configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/practice_ims
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#configuration to setup swagger page
springdoc.swagger-ui.use-root-path=true
springdoc.writer-default-pretty-printer=true
springdoc.swagger-ui,disable-swagger-default-url=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

#logging.level.org.springdoc=DEBUG
#logging.level.org.springframework.web=DEBUG


#To run the application in debug mode
#debug=true