/*
-- Lab Order Hdr
drop table if exists lab_order_hdr;
*/

-- Lab Order Hdr
CREATE TABLE IF NOT EXISTS lab_order_hdr(
    --Main Columns
    lab_name VARCHAR(100),
    lab_test_name VARCHAR(200),
    description VARCHAR(1000),
    note VARCHAR(1000),

    --Inherited Columns
    tran_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_active bool DEFAULT TRUE NOT NULL
);
