#////////////////////////////////////////////////
#//
#// Name: application.properties
#//
#// Description:
#//
#// Version history:
#//
#// v1.1 || type : New Func || Jun 16, 2026 || TaukirS (ER 1001 - Project Setup for patient mst)
#////////////////////////////////////////////////
spring.application.name=IMS_v2

#//Start Jun 15, 2026 TaukirS (ER 1001 - Project Setup for patient mst)
#changed the port of the server for accessing it.
server.port=9081

#connect the postgres DB with the server.
spring.datasource.url=jdbc:postgresql://localhost:5432/practice_ims_v2
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
