#////////////////////////////////////////////////
#//
#// Name: application.properties
#//
#// Description:
#//
#// Version history:
#//
#// v1.1 || type : New Func || Jun 16, 2026 || TaukirS (ER 1001 - Project Setup for patient mst)
#// v1.2 || type : Change || Jul 24, 2026 || TaukirS (ER 1007 - logging and dto to record changes)
#////////////////////////////////////////////////
spring.application.name=IMS_v2

#//Start Jun 15, 2026 TaukirS (ER 1001 - Project Setup for patient mst)
#changed the port of the server for accessing it.
server.port=9081

#//Jun 19, 2026 TaukirS (ER 1002 - patient mst apis)
#server.servlet.context-path="/ims"

#connect the postgres DB with the server.
spring.datasource.url=jdbc:postgresql://localhost:5432/practice_ims_v2
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#//Jul 24, 2026 TaukirS (ER 1007 - logging and dto to record changes)
logging.level.com.tsTech.practice.IMS_v2 = debug