#////////////////////////////////////////////////
#//
#// Name: discovery-service application.properties
#//
#// Description:
#//
#// Version history:
#//
#// v1.1 || type : Change || Apr 01, 2026 || TaukirS (ER 1106 - Eureka servier config)
#////////////////////////////////////////////////
spring.application.name=discovery-service

#service port config
server.port=8761

#Eureka server configs
eureka.client.register-with-eureka=false
eureka.client.fetch.repository=false