/*

drop table if exists visit_type;

*/

CREATE TABLE IF NOT EXISTS visit_type(
    tran_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_active bool DEFAULT TRUE NOT NULL,
    name varchar(50) UNIQUE,
    note varchar(1000),

    CONSTRAINT visit_type_pkey primary key (tran_id)
);