/*
drop table if exists visit_note;
drop index if exists idx_visit_note_patient_id;
*/

CREATE TABLE IF NOT EXISTS visit_note(
    tran_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_active bool DEFAULT TRUE NOT NULL,
--Main Columns
    description VARCHAR(100),
    patient_id BIGINT NOT NULL,
    office_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    is_billable bool,
    visit_type_id BIGINT NOT NULL,
    encounter_date DATE,
    procedure VARCHAR(200),
    note VARCHAR(1000),

    CONSTRAINT fk_visit_note_patient_mst_sb_tran_id FOREIGN KEY(patient_id) REFERENCES patient_mst_sb(tran_id),
    CONSTRAINT fk_visit_note_office_mst_sb_tran_id FOREIGN KEY(office_id) REFERENCES office_mst_sb(tran_id),
    CONSTRAINT fk_visit_note_doctor_mst_sb_tran_id FOREIGN KEY(provider_id) REFERENCES doctor_mst_sb(tran_id),
    CONSTRAINT fk_visit_note_visit_type_tran_id FOREIGN KEY(visit_type_id) REFERENCES visit_type(tran_id)
);

CREATE INDEX IF NOT EXISTS idx_visit_note_patient_id ON visit_note (patient_id);
CREATE INDEX IF NOT EXISTS idx_visit_note_office_id_provider_id ON visit_note (office_id, provider_id);