/*
-- VnCareplan Mst
drop table if exists vn_careplan_mst;
drop index if exists idx_vn_careplan_mst_pn_id_careplan_id;
*/

-- VisitNote Careplan Mst
CREATE TABLE IF NOT EXISTS vn_careplan_mst(
    --Main Columns
    description VARCHAR(1000),
    seq BIGINT,
    pn_id BIGINT,
    careplan_id BIGINT,

    --Inherited Columns
    tran_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_active bool DEFAULT TRUE NOT NULL,

    CONSTRAINT fk_vn_careplan_mst_visit_note_tran_id FOREIGN KEY (pn_id) REFERENCES visit_note(tran_id),
    CONSTRAINT fk_vn_careplan_mst_careplan_mst_tran_id FOREIGN KEY (careplan_id) REFERENCES careplan_mst(tran_id)
);

CREATE INDEX IF NOT EXISTS idx_vn_careplan_mst_pn_id_careplan_id on vn_careplan_mst(pn_id desc, careplan_id desc);
