/*
-- VnCareplan Mst
drop table if exists vn_careplan_icd_map;
drop index if exists idx_vn_careplan_icd_map_vn_careplan_id_desc;
*/

-- VisitNote Careplan Mst
CREATE TABLE IF NOT EXISTS vn_careplan_icd_map(
    --Main Columns
    vn_careplan_id BIGINT NOT NULL,
    icd_id BIGINT NOT NULL,
    seq BIGINT NOT NULL,

    --Inherited Columns
    tran_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_active bool DEFAULT TRUE NOT NULL,

    --Foreign key constraints
    CONSTRAINT fk_vn_careplan_icd_mapping_vn_careplan_mst_tran_id FOREIGN KEY(vn_careplan_id) REFERENCES vn_careplan_mst(tran_id),
    CONSTRAINT fk_vn_careplan_icd_mapping_icd_mst_tran_id FOREIGN KEY(icd_id) REFERENCES icd_mst(tran_id),
    --General
    CONSTRAINT chk_vn_careplan_icd_map_seq_1_to_8 CHECK(seq >=1 AND seq<=8),
    --Unique constraint
    CONSTRAINT uk_vn_careplan_icd_map_vn_careplan_id_seq UNIQUE(vn_careplan_id, seq)
);

CREATE INDEX IF NOT EXISTS idx_vn_careplan_icd_map_vn_careplan_id_desc on vn_careplan_icd_map(vn_careplan_id desc);
