/*
-- Diagnosis ICD Mapping
drop table if exists diagnosis_icd_mapping;
drop index if exists idx_diagnosis_icd_mapping_diagnosis_id_icd_id;

-- Diagnosis Mst
drop table if exists diagnosis_mst;
drop index if exists idx_diagnosis_mst_patient_id_desc;
drop index if exists idx_diagnosis_mst_pn_id_desc;
*/

-- Diagnosis Mst
CREATE TABLE IF NOT EXISTS diagnosis_mst(
    tran_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_active bool DEFAULT TRUE NOT NULL,
--Main Columns
    patient_id BIGINT NOT NULL,
    pn_id BIGINT NOT NULL,
    taken_at DATE NOT NULL,
    note VARCHAR(1000),

    CONSTRAINT fk_diagnosis_mst_patient_mst_sb_tran_id FOREIGN KEY(patient_id) REFERENCES patient_mst_sb(tran_id),
    CONSTRAINT fk_diagnosis_mst_visit_note_tran_id FOREIGN KEY(pn_id) REFERENCES visit_note(tran_id)
);

CREATE INDEX IF NOT EXISTS idx_diagnosis_mst_patient_id_desc ON diagnosis_mst (patient_id DESC);
CREATE INDEX IF NOT EXISTS idx_diagnosis_mst_pn_id_desc ON diagnosis_mst (pn_id DESC);

-- Diagnosis ICD Mapping
CREATE TABLE IF NOT EXISTS diagnosis_icd_mapping(
    tran_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_active bool DEFAULT TRUE NOT NULL,
--Main Columns
    diagnosis_id BIGINT NOT NULL,
    icd_id BIGINT NOT NULL,
    seq BIGINT NOT NULL,

--Foreign key constraints
    CONSTRAINT fk_diagnosis_icd_mapping_diagnosis_mst_tran_id FOREIGN KEY(diagnosis_id) REFERENCES diagnosis_mst(tran_id),
    CONSTRAINT fk_diagnosis_icd_mapping_icd_mst_tran_id FOREIGN KEY(icd_id) REFERENCES icd_mst(tran_id),
--General
    CONSTRAINT chk_diagnosis_icd_mapping_seq_1_to_8 CHECK(seq >=1 AND seq<=8),
--Unique constraint
    CONSTRAINT uk_diagnosis_icd_mapping_diagnosis_id_seq UNIQUE(diagnosis_id, seq)
    );

CREATE INDEX IF NOT EXISTS idx_diagnosis_icd_mapping_diagnosis_id_icd_id ON diagnosis_icd_mapping (diagnosis_id, icd_id);
