#////////////////////////////////////////////////
#//
#// Name:
#//
#// Description:
#//
#// Version history:
#//
#// v1.1 || type : Change || Apr 01, 2026 || TaukirS (ER 1106 - Eureka servier config)
#////////////////////////////////////////////////
spring.application.name=api-gateway


#Server port config
server.port=9001